# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflocalexpand" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "c0eb6dffac36b74d003e1db2508bdfadadbe0f69f39d823fba4b2f9f43d23e59"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a79226405955e9b96861308269df8eb4ad829681d26a3a998c0a4a3d550a25d"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8750b3fce790fee1a23afeb29103d89b8d869248a1e9ef169ae0516374a3b917"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e0df19faee6efa2038a7199012d27368938e8e823860668e9aae8f2bce9d599"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tflocalexpand"
  desc "tflocalexpand is a tool to expand Terraform locals references into their underlying expressions."
  homepage "https://github.com/winebarrel/tflocalexpand"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflocalexpand"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflocalexpand"]
    end
  end

  # No zap stanza required

end
