# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflocalexpand" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "d12e167cfa48618511043fdc384b39c71bd02787f829c3d16cafa470901f0669"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ced3292d65f18f4060097a10ac52fc36b11d0f0297669699d920726787bf47d3"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e942170543e99452cb7cfd5a20bf74c21d6d95ba17647494a00d0e6aa79c7793"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9bff1e4abdfd4e3e308a24007eee3e9a709bc6875cc022638e1b8f51ead4a9a"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tflocalexpand"
  desc "tflocalexpand is a tool to expand Terraform locals references into their underlying expressions."
  homepage "https://github.com/winebarrel/tflocalexpand"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflocalexpand"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflocalexpand"]
    end
  end

  # No zap stanza required

end
