# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflocalexpand" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "fa6254c808c8c6c2f71b3a76a06b60b78acaf178c7c18635d78ee9367283d5e7"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c20aef9f9e6b6cd41ea66e56aebce7c90938dec0b28e1f2569e0b81732e958b"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0cde6215591a22c1b2d6b5012d5af418ee9f2ddaa8149d2b2a5619615182d25"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b75f5fc33f47981bc64c42a5dadd793c795ddd67a2fb65d329470e317c2c97c4"
      url "https://github.com/winebarrel/tflocalexpand/releases/download/v#{version}/tflocalexpand_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tflocalexpand"
  desc "tflocalexpand is a tool to expand Terraform locals references into their underlying expressions."
  homepage "https://github.com/winebarrel/tflocalexpand"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflocalexpand"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflocalexpand"]
    end
  end

  # No zap stanza required

end
